### ISSUE TITLE
你好，我想请问一下，在使用真实结肠镜的图片的时候，是否经过畸变矫正？非常感谢

### ISSUE THREAD

**Issue by liuyq055** [ckLibra/Self-Supervised-Depth-Estimation-for-Colonoscopy#1]

**Comment by ckLibra** [comment]
Yeah. We undistort the images.

**Comment by liuyq055** [comment]
Could you kindly inform which camera model is used? Pinhole camera or Fisheye? Thank you very much

**Comment by ckLibra** [comment]
Opencv has the api for camera calibration. Since we have the colonoscopy camera, so we use it to capture the images of black-white checkerboard. Then we assume the camera model as the fisheye, estimating its parameters based on the calibration algorithm. Then we undistort the images to convert the fisheye model to the pinhole camera. If you only have the colonoscopy images, you can just assume it as the fisheye camera to estimate the distortion parameters, then undistort the images. After that, you can just use the pinhole camera model.

**Comment by liuyq055** [comment]
> Opencv has the api for camera calibration. Since we have the colonoscopy camera, so we use it to capture the images of black-white checkerboard. Then we assume the camera model as the fisheye, estimating its parameters based on the calibration algorithm. Then we undistort the images to convert the fisheye model to the pinhole camera. If you only have the colonoscopy images, you can just assume it as the fisheye camera to estimate the distortion parameters, then undistort the images. After that, you can just use the pinhole camera model.

Thank you!
